spring.application.name=brainRot

spring.datasource.url = jdbc:h2:file:./data/post_data
spring.datasource.driverClassName = org.h2.Driver

 "enable h2-console"
spring.h2.console.enabled = true

 "username and password"
spring.datasource.username=b
spring.datasource.password=b

 "show sql commands"
spring.jpa.show-sql=true

 "the data doesnt get lost when reloaded"
spring.jpa.hibernate.ddl-auto=update